using System.Text;
using RefactorScope.Core.Orchestration;
using RefactorScope.Core.Results;

namespace RefactorScope.Core.Reporting
{
    /// <summary>
    /// Exporta relatório arquitetural em formato Markdown.
    /// Utiliza Zombie efetivo (probabilístico se disponível).
    /// </summary>
    public sealed class MarkdownReportExporter
    {
        public void Export(ConsolidatedReport report, string outputPath)
        {
            var sb = new StringBuilder();

            var architecture = report.GetResult<ArchitecturalClassificationResult>();
            var isolated = report.GetResult<CoreIsolationResult>();
            var coupling = report.GetResult<CouplingResult>();
            var fitness = report.GetResult<FitnessGateResult>();

            if (architecture == null)
                return;

            var threshold = 0.60;
            var effectiveZombies = report.GetEffectiveZombieTypes();

            sb.AppendLine("# 🧬 RefactorScope – Relatório Arquitetural");
            sb.AppendLine();
            sb.AppendLine($"📅 **Execution Time:** {report.ExecutionTime:yyyy-MM-dd HH:mm} UTC  ");
            sb.AppendLine($"📂 **Target Scope:** `{report.TargetScope}`  ");
            sb.AppendLine();
            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine("## 🏥 Architectural Health by Module");
            sb.AppendLine();

            var modules = architecture.Items.GroupBy(i => i.Folder);

            foreach (var module in modules)
            {
                var total = module.Count();
                if (total == 0) continue;

                var zombieCount = effectiveZombies
                    .Count(z => module.Any(m => m.TypeName == z));

                var isolatedCount = isolated?.IsolatedCoreTypes
                    .Count(i => module.Any(m => m.TypeName == i)) ?? 0;

                var fanOut = coupling?.ModuleFanOut
                    .GetValueOrDefault(module.Key) ?? 0;

                var zombieRate = zombieCount / (double)total;
                var isolationRate = isolatedCount / (double)total;
                var couplingRate = fanOut / (double)total;
                var coreDensity = module.Count(t => t.Layer == "Core") / (double)total;

                var score =
                    100
                    - (couplingRate * 30)
                    - (zombieRate * 25)
                    - (isolationRate * 20)
                    + (coreDensity * 15);

                score = Math.Max(0, Math.Min(100, score));

                var scoreEmoji = score >= 70 ? "🟢"
                                 : score >= 40 ? "🟡"
                                 : "🔴";

                sb.AppendLine($"### {scoreEmoji} {module.Key}");
                sb.AppendLine();
                sb.AppendLine($"- **Score:** `{score:0.0}`");
                sb.AppendLine($"- **Zombies:** {(zombieCount > 0 ? "🔴" : "🟢")} {zombieCount} ({zombieRate:0%})");
                sb.AppendLine($"- **Coupling:** {couplingRate:0.00}");
                sb.AppendLine($"- **Isolation:** {isolationRate:0.00}");
                sb.AppendLine();
            }

            if (fitness != null)
            {
                sb.AppendLine("---");
                sb.AppendLine();
                sb.AppendLine("## 🚦 Fitness Gates");
                sb.AppendLine();

                foreach (var gate in fitness.Gates)
                {
                    var emoji = gate.Status switch
                    {
                        GateStatus.Pass => "🟢",
                        GateStatus.Warn => "🟡",
                        GateStatus.Fail => "🔴",
                        _ => "⚪"
                    };

                    sb.AppendLine($"- {emoji} **{gate.GateName}** {gate.Message}");
                }

                sb.AppendLine();
                sb.AppendLine(fitness.HasFailure
                    ? "🔴 **Arquitetura NÃO pronta para CI/CD**"
                    : "🟢 **Arquitetura pronta para CI/CD**");
            }

            sb.AppendLine();
            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine("_Generated by RefactorScope_");

            File.WriteAllText(outputPath, sb.ToString());
        }
    }
}