using RefactorScope.Analyzers.Solid;
using RefactorScope.Core.Analyzers;
using RefactorScope.Core.Model;
using RefactorScope.Core.Results;
using RefactorScope.Exporters.Styling;
using RefactorScope.Exporters.Dashboards.Renderers;
using System.Text;

namespace RefactorScope.Exporters.Dashboards
{
    public sealed class StructuralInventoryExporter
    {
        public void Export(
            ConsolidatedReport report,
            string htmlPath,
            string themeFileName)
        {
            var html = GenerateHtml(report, themeFileName);
            File.WriteAllText(htmlPath, html, Encoding.UTF8);
        }

        private string GenerateHtml(
            ConsolidatedReport report,
            string themeFileName)
        {


            var classification = report.Results
                .OfType<ArchitecturalClassificationResult>()
                .FirstOrDefault();

            var solid = report.Results
                .OfType<SolidResult>()
                .FirstOrDefault();

            if (classification == null)
            {
                return DashboardHtmlShell.RenderDocumentStart(
                           "Structural Dashboard",
                           themeFileName)
                       + """
<div class="topbar" augmented-ui="tl-clip tr-clip bl-clip br-clip border">
    <div class="brand">
        <div class="brand-kicker">RefactorScope // Structural Module</div>
        <h1>Structural Dashboard</h1>
        <div class="subtitle">No structural classification result available.</div>
    </div>
</div>
"""
                       + DashboardHtmlShell.RenderDocumentEnd(
                           "Generated by RefactorScope Structural Dashboard");
            }

            var items = classification.Items;
            var hygiene = new ArchitecturalHygieneAnalyzer().Analyze(report);
            var breakdown = report.GetStructuralCandidateBreakdown();
            var namespaceCount = CountDistinctNamespaces(items);
            var candidatesCount = breakdown.StructuralCandidates;
            var confirmedCount = breakdown.ProbabilisticConfirmed;
            var suspiciousCount = breakdown.Suspicious;
            var patternSimilarityCount = breakdown.PatternSimilarity;

            var confirmed = report.GetEffectiveUnresolvedCandidates().ToHashSet();
            var suspicious = report.GetPatternSimilarityCandidates().ToHashSet();

            var implicitCoupling = report.Results
                .OfType<ImplicitCouplingResult>()
                .FirstOrDefault();

            var coupling = report.Results
                .OfType<CouplingResult>()
                .FirstOrDefault();

            var couplingSuspects = implicitCoupling?.Suspicions.Count ?? 0;
            var solidAlerts = solid?.Alerts.Count ?? 0;

            double avgAbstractness = 0;
            double avgInstability = 0;
            double avgDistance = 0;

            if (coupling != null && coupling.AbstractnessByModule.Any())
            {
                avgAbstractness = coupling.AbstractnessByModule.Values.Average();
                avgInstability = coupling.InstabilityByModule.Values.Average();
                avgDistance = coupling.DistanceByModule.Values.Average();
            }

            var targetName = string.IsNullOrWhiteSpace(report.TargetScope)
                ? "Unknown Scope"
                : Path.GetFileName(report.TargetScope.TrimEnd(
                    Path.DirectorySeparatorChar,
                    Path.AltDirectorySeparatorChar));

            var namespaceDriftItems = items
                .Where(HasNamespaceDrift)
                .OrderBy(i => GetFolderPath(report, i.DeclaredInFile))
                .ThenBy(i => i.TypeName)
                .ToList();

            var sb = new StringBuilder();

            sb.AppendLine(DashboardHtmlShell.RenderDocumentStart(
                "Structural Dashboard",
                themeFileName));

            sb.AppendLine($"""
<div class="topbar" augmented-ui="tl-clip tr-clip bl-clip br-clip border">
    <div class="brand">
        <div class="brand-kicker">RefactorScope // Structural Module</div>
        <h1>Structural Dashboard</h1>
        <div class="subtitle">Target Project: <b>{Html(targetName)}</b></div>
    </div>

    <div class="run-meta">
        <div><b>Generated:</b> {report.ExecutionTime:dd-MM-yyyy HH:mm} UTC</div>
        <div><b>Scope:</b> {Html(report.TargetScope)}</div>
        <div><b>Total Types:</b> {hygiene.TotalClasses}</div>
        <div><b>Hygiene:</b> {Html(hygiene.HygieneLevel)}</div>
    </div>
</div>
""");
            sb.AppendLine("""
<div class="section">
    <div class="section-title">
        <h2>Structural Signal Grid</h2>
        <div class="line"></div>
    </div>
</div>
""");

            sb.AppendLine($"""
<div class="grid-kpis structural-kpis">
    <div class="kpi" augmented-ui="tr-clip bl-clip border">
        <div class="label">Total Classes</div>
        <div class="value">{hygiene.TotalClasses}</div>
        <div class="hint">Total number of structurally classified types</div>
    </div>

    <div class="kpi" augmented-ui="tr-clip bl-clip border">
    <div class="label">Namespaces</div>
    <div class="value">{namespaceCount}</div>
    <div class="hint">Distinct namespaces represented in the scope</div>
</div>

    <div class="kpi warning" augmented-ui="tr-clip bl-clip border">
        <div class="label">Dead Code Candidates</div>
        <div class="value">{candidatesCount}</div>
        <div class="hint">Possible dead code types</div>
    </div>

    <div class="kpi good" augmented-ui="tr-clip bl-clip border">
        <div class="label">Pattern Similarity</div>
        <div class="value">{patternSimilarityCount}</div>
        <div class="hint">Candidates compatible with known architectural patterns</div>
    </div>

    <div class="kpi alert" augmented-ui="tr-clip bl-clip border">
        <div class="label">Unresolved</div>
        <div class="value">{confirmedCount}</div>
        <div class="hint">Candidates who could not be refuted as dead code</div>
    </div>

    <div class="kpi {(hygiene.NamespaceDriftCount > 0 ? "warning" : "good")}" augmented-ui="tr-clip bl-clip border">
        <div class="label">Namespace Drift</div>
        <div class="value">{hygiene.NamespaceDriftCount}</div>
        <div class="hint">Types whose namespace remains incompatible with folder structure</div>
    </div>

    <div class="kpi {(hygiene.GlobalNamespaceCount > 0 ? "warning" : "good")}" augmented-ui="tr-clip bl-clip border">
        <div class="label">Global Namespace</div>
        <div class="value">{hygiene.GlobalNamespaceCount}</div>
        <div class="hint">Types declared without an explicit namespace boundary</div>
    </div>

    <div class="kpi good" augmented-ui="tr-clip bl-clip border">
        <div class="label">Isolated Core</div>
        <div class="value">{hygiene.IsolatedCoreCount}</div>
        <div class="hint">Number of core types structurally isolated from outer layers</div>
    </div>

    <div class="kpi {(hygiene.SmellIndex > 40 ? "alert" : hygiene.SmellIndex > 20 ? "warning" : "good")}" augmented-ui="tr-clip bl-clip border">
        <div class="label">Code Smell Index</div>
        <div class="value">{hygiene.SmellIndex:0.0}</div>
        <div class="hint">Composite structural hygiene score. Lower is better</div>
    </div>

    <div class="kpi {(couplingSuspects > 0 ? "warning" : "good")}" augmented-ui="tr-clip bl-clip border">
        <div class="label">Implicit Coupling</div>
        <div class="value">{couplingSuspects}</div>
        <div class="hint">Types suggesting concentrated dependency flow toward specific modules</div>
    </div>

    <div class="kpi {(solidAlerts > 0 ? "warning" : "good")}" augmented-ui="tr-clip bl-clip border">
        <div class="label">SOLID Alerts</div>
        <div class="value">{solidAlerts}</div>
        <div class="hint">Heuristic object-oriented design signals that deserve review</div>
    </div>

    <div class="kpi" augmented-ui="tr-clip bl-clip border">
        <div class="label">A / I / D</div>
        <div class="value" style="font-size:22px;">{avgAbstractness:0.00} / {avgInstability:0.00} / {avgDistance:0.00}</div>
        <div class="hint">Average abstractness, instability and distance from main sequence</div>
    </div>
</div>
""");

            sb.AppendLine("""
<div class="section">
    <div class="section-title">
        <h2>Executive Structural Reading</h2>
        <div class="line"></div>
    </div>
    <div class="dual">
""");

            sb.AppendLine($"""
<div class="panel" augmented-ui="tl-clip tr-clip bl-clip br-clip border">
    <h3>Structural Interpretation</h3>
    <ul class="clean">
        <li>{Html(GetCoreDiagnosis(hygiene))}</li>
        <li>{Html(GetNamespaceDiagnosis(hygiene))}</li>
        <li>{Html(GetGlobalNamespaceDiagnosis(hygiene))}</li>
        <li>{Html(GetUnresolvedDiagnosis(breakdown))}</li>
        <li>{Html(GetSolidDiagnosis(solid))}</li>
        <li>{Html(GetImplicitCouplingDiagnosis(hygiene, implicitCoupling))}</li>
    </ul>

    <div style="margin-top:16px;">
        <div class="badge {(confirmedCount > 0 ? "red" : "green")}"><span class="badge-dot"></span> Unresolved: {confirmedCount}</div>
        <div class="badge {(hygiene.NamespaceDriftCount > 0 ? "amber" : "green")}" style="margin-top:8px;"><span class="badge-dot"></span> Namespace Drift: {hygiene.NamespaceDriftCount}</div>
        <div class="badge {(solidAlerts > 0 ? "amber" : "green")}" style="margin-top:8px;"><span class="badge-dot"></span> SOLID Alerts: {solidAlerts}</div>
        <div class="badge {(couplingSuspects > 0 ? "amber" : "green")}" style="margin-top:8px;"><span class="badge-dot"></span> Implicit Coupling: {couplingSuspects}</div>
    </div>
</div>
""");

            sb.AppendLine($"""
<div class="panel" augmented-ui="tl-clip tr-clip bl-clip br-clip border">
    <h3>Method Snapshot</h3>
    <ul class="clean">
        <li><b>Structural Candidates:</b> types with zero structural references in the parsed graph.</li>
        <li><b>Pattern Similarity:</b> candidate classes compatible with known structural patterns.</li>
        <li><b>Unresolved:</b> strongest dead-code or broken-link signal after refinement.</li>
        <li><b>Implicit Coupling:</b> dependency concentration toward a dominant module.</li>
        <li><b>A / I / D:</b> Robert Martin architectural balance indicators.</li>
    </ul>
</div>
""");

            sb.AppendLine("</div></div>");

            sb.AppendLine("""
<div class="section">
    <div class="section-title">
        <h2>Charts & Diagnostics</h2>
        <div class="line"></div>
    </div>
    <div class="panel" augmented-ui="tl-clip tr-clip bl-clip br-clip border">
""");

            sb.AppendLine(RenderCharts(
                breakdown,
                hygiene,
                solid,
                implicitCoupling,
                coupling));

            sb.AppendLine("""
    </div>
</div>
""");

            sb.AppendLine("""
<div class="section">
    <div class="section-title">
        <h2>Structural Candidate Matrix</h2>
        <div class="line"></div>
    </div>
    <div class="panel" augmented-ui="tl-clip tr-clip bl-clip br-clip border">
""");

            sb.AppendLine("""
<div style="margin-bottom:16px;">
    <input id="search"
           type="text"
           onkeyup="searchTable()"
           placeholder="Search class, folder, status..."
           style="width:100%; padding:12px; border-radius:10px; border:1px solid rgba(255,255,255,0.14); background:rgba(255,255,255,0.03); color:#fff;" />
</div>
""");

            sb.AppendLine("""
<div class="table-shell">
<table id="table" class="link-table structural-table">
    <thead>
        <tr>
            <th onclick="sortTable(0)">Class</th>
            <th onclick="sortTable(1)">Folder</th>
            <th onclick="sortTable(2)">Uses</th>
            <th onclick="sortTable(3)">Status</th>
            <th onclick="sortTable(4)">Removal</th>
        </tr>
    </thead>
    <tbody>
""");

            int GetPriority(ArchitecturalClassificationItem item)
            {
                if (confirmed.Contains(item.TypeName))
                    return 0;

                if (suspicious.Contains(item.TypeName))
                    return 1;

                if (item.Layer == "Core")
                    return 2;

                return 3;
            }

            var orderedItems = items
                .OrderBy(GetPriority)
                .ThenBy(i => i.TypeName)
                .ToList();

            foreach (var item in orderedItems)
            {
                string rowClass = "";

                if (confirmed.Contains(item.TypeName))
                    rowClass = "class='row-alert'";
                else if (suspicious.Contains(item.TypeName))
                    rowClass = "class='row-warning'";
                else if (item.Layer == "Core")
                    rowClass = "class='row-core'";

                var displayClass = Html(GetDisplayClassName(item));
                var displayFolder = Html(GetFolderPath(report, item.DeclaredInFile));
                var displayStatus = Html(TranslateStatus(item.Status));
                var displayRemoval = Html(TranslateRemoval(item.RemovalCandidate));

                sb.AppendLine($"""
<tr {rowClass}>
    <td>{displayClass}</td>
    <td>{displayFolder}</td>
    <td>{item.UsageCount}</td>
    <td>{displayStatus}</td>
    <td>{displayRemoval}</td>
</tr>
""");
            }

            sb.AppendLine("""
    </tbody>
</table>
</div>
</div>
""");

            if (namespaceDriftItems.Any())
            {
                sb.AppendLine("""
<div class="section">
    <div class="section-title">
        <h2>Namespace Drift Review</h2>
        <div class="line"></div>
    </div>
    <div class="panel" augmented-ui="tl-clip tr-clip bl-clip br-clip border">
        <table class="link-table">
            <thead>
                <tr>
                    <th>Class</th>
                    <th>Folder</th>
                    <th>Namespace</th>
                    <th>Expected Namespace</th>
                </tr>
            </thead>
            <tbody>
""");

                foreach (var item in namespaceDriftItems)
                {
                    var folder = GetFolderPath(report, item.DeclaredInFile);
                    var expectedNamespace = BuildExpectedNamespace(report, item.DeclaredInFile);

                    sb.AppendLine($"""
<tr class="row-warning">
    <td>{Html(GetDisplayClassName(item))}</td>
    <td>{Html(folder)}</td>
    <td>{Html(item.Namespace)}</td>
    <td>{Html(expectedNamespace)}</td>
</tr>
""");
                }

                sb.AppendLine("""
            </tbody>
        </table>
    </div>
</div>
""");
            }

            if (implicitCoupling != null && implicitCoupling.Suspicions.Any())
            {
                sb.AppendLine("""
<div class="section">
    <div class="section-title">
        <h2>Implicit Coupling Candidates</h2>
        <div class="line"></div>
    </div>
    <div class="panel" augmented-ui="tl-clip tr-clip bl-clip br-clip border">
        <table class="link-table">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Module</th>
                    <th>Target Module</th>
                    <th>Fan-Out</th>
                    <th>Fan-In</th>
                    <th>Dominance</th>
                    <th>Volume</th>
                </tr>
            </thead>
            <tbody>
""");

                foreach (var s in implicitCoupling.Suspicions)
                {
                    sb.AppendLine($"""
<tr>
    <td>{Html(s.TypeName)}</td>
    <td>{Html(s.Module)}</td>
    <td>{Html(s.TargetModule)}</td>
    <td>{s.FanOut}</td>
    <td>{s.FanIn}</td>
    <td>{s.Dominance:0.00}</td>
    <td>{s.Volume}</td>
</tr>
""");
                }

                sb.AppendLine("""
            </tbody>
        </table>

        <div style="margin-top:12px;" class="muted">
            <b>Fan-Out</b> = outgoing dependencies |
            <b>Fan-In</b> = incoming dependencies |
            <b>Dominance</b> = relative structural concentration |
            <b>Volume</b> = dependency interaction load
        </div>
    </div>
</div>
""");
            }

            if (solid != null && solid.Alerts.Any())
            {
                sb.AppendLine("""
<div class="section">
    <div class="section-title">
        <h2>SOLID Alerts</h2>
        <div class="line"></div>
    </div>
    <div class="panel" augmented-ui="tl-clip tr-clip bl-clip br-clip border">
        <table class="link-table">
            <thead>
                <tr>
                    <th>Principle</th>
                    <th>Class</th>
                    <th>Namespace</th>
                    <th>Reason</th>
                </tr>
            </thead>
            <tbody>
""");

                foreach (var alert in solid.Alerts)
                {
                    sb.AppendLine($"""
<tr>
    <td>{Html(alert.Principle.ToString())}</td>
    <td>{Html(alert.ClassName)}</td>
    <td>{Html(alert.Namespace)}</td>
    <td>{Html(alert.Reason)}</td>
</tr>
""");
                }

                sb.AppendLine("""
            </tbody>
        </table>
    </div>
</div>
""");
            }

            sb.AppendLine("""
<div class="section">
    <div class="section-title">
        <h2>Methodology & Limitations</h2>
        <div class="line"></div>
    </div>
    <div class="panel" augmented-ui="tl-clip tr-clip bl-clip br-clip border">
        <ul class="clean">
            <li>This dashboard is based on heuristic static structural analysis.</li>
            <li>Structural Candidates are not automatically dead code.</li>
            <li>Pattern Similarity often indicates intentional architecture, not removal targets.</li>
            <li>Unresolved candidates are the strongest manual-review bucket.</li>
            <li>Reflection, DI wiring and framework conventions may generate false positives.</li>
            <li>Final decisions should always include human review.</li>
        </ul>
    </div>
</div>
""");

            sb.AppendLine("""
<style>
.grid-kpis.structural-kpis {
    display: grid;
    grid-template-columns: repeat(6, minmax(0, 1fr));
    gap: 16px;
}

@media (max-width: 1400px) {
    .grid-kpis.structural-kpis {
        grid-template-columns: repeat(4, minmax(0, 1fr));
    }
}

@media (max-width: 980px) {
    .grid-kpis.structural-kpis {
        grid-template-columns: repeat(2, minmax(0, 1fr));
    }
}

.table-shell {
    max-height: 720px;
    overflow-y: auto;
    overflow-x: auto;
    border: 1px solid rgba(255,255,255,0.08);
    border-radius: 12px;
}

.structural-table thead th {
    position: sticky;
    top: 0;
    z-index: 2;
    background: rgba(8, 18, 40, 0.96);
    backdrop-filter: blur(4px);
}

.row-alert td {
    background: rgba(255, 90, 90, 0.14);
}

.row-warning td {
    background: rgba(255, 196, 0, 0.11);
}

.row-core td {
    background: rgba(64, 160, 255, 0.12);
}

.dashboard-nav-row {
    display: flex;
    flex-wrap: nowrap;
    gap: 12px;
    overflow-x: auto;
    overflow-y: hidden;
    white-space: nowrap;
    padding-bottom: 2px;
}

.dashboard-nav-row .badge {
    flex: 0 0 auto;
}

.dashboard-nav-row::-webkit-scrollbar {
    height: 8px;
}

.dashboard-nav-row::-webkit-scrollbar-thumb {
    background: rgba(255,255,255,0.12);
    border-radius: 999px;
}
</style>

<script>
function searchTable() {
  var input = document.getElementById('search');
  var filter = input.value.toLowerCase();
  var table = document.getElementById('table');
  var rows = table.getElementsByTagName('tr');

  for (var i = 1; i < rows.length; i++) {
    rows[i].style.display = rows[i].innerText.toLowerCase().includes(filter) ? '' : 'none';
  }
}

function sortTable(n) {
  var table = document.getElementById('table');
  var switching = true;
  var dir = 'asc';

  while (switching) {
    switching = false;
    var rows = table.rows;

    for (var i = 1; i < rows.length - 1; i++) {
      var x = rows[i].getElementsByTagName('TD')[n];
      var y = rows[i + 1].getElementsByTagName('TD')[n];
      var shouldSwitch = false;

      if (!x || !y) continue;

      if (dir === 'asc' && x.innerText.toLowerCase() > y.innerText.toLowerCase()) shouldSwitch = true;
      if (dir === 'desc' && x.innerText.toLowerCase() < y.innerText.toLowerCase()) shouldSwitch = true;

      if (shouldSwitch) {
        rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
        switching = true;
      }
    }

    if (!switching && dir === 'asc') {
      dir = 'desc';
      switching = true;
    }
  }
}
</script>
""");

            sb.AppendLine(DashboardHtmlShell.RenderDocumentEnd(
                "Generated by RefactorScope Structural Dashboard // Shared Hub Layout"));

            return sb.ToString();
        }

        private string RenderCharts(
            StructuralCandidateAnalysisBreakdown breakdown,
            HygieneReport hygiene,
            SolidResult? solid,
            ImplicitCouplingResult? implicitCoupling,
            CouplingResult? coupling)
        {
            var sb = new StringBuilder();
            var render = new ChartsRendererP5();

            sb.AppendLine("<div style='display:flex; gap:32px; flex-wrap:wrap; align-items:flex-start;'>");
            sb.AppendLine(render.RenderRadarSvgEnhanced(hygiene, breakdown, solid, implicitCoupling));

            if (coupling != null)
                sb.AppendLine(render.RenderArchitecturalGalaxyEnhanced(coupling));

            sb.AppendLine("<div style='flex:1; min-width:280px;'>");
            sb.AppendLine("<ul class='clean'>");
            sb.AppendLine($"<li>{Html(GetCoreDiagnosis(hygiene))}</li>");
            sb.AppendLine($"<li>{Html(GetNamespaceDiagnosis(hygiene))}</li>");
            sb.AppendLine($"<li>{Html(GetGlobalNamespaceDiagnosis(hygiene))}</li>");
            sb.AppendLine($"<li>{Html(GetUnresolvedDiagnosis(breakdown))}</li>");
            sb.AppendLine($"<li>{Html(GetSolidDiagnosis(solid))}</li>");
            sb.AppendLine($"<li>{Html(GetImplicitCouplingDiagnosis(hygiene, implicitCoupling))}</li>");
            sb.AppendLine("</ul>");
            sb.AppendLine("</div>");
            sb.AppendLine("</div>");

            return sb.ToString();
        }

        private static string GetDisplayClassName(ArchitecturalClassificationItem item)
        {
            if (!string.IsNullOrWhiteSpace(item.DeclaredInFile))
                return Path.GetFileName(item.DeclaredInFile);

            return item.TypeName + ".cs";
        }

        private static string GetFolderPath(ConsolidatedReport report, string? declaredInFile)
        {
            if (string.IsNullOrWhiteSpace(declaredInFile))
                return string.Empty;

            var normalized = declaredInFile
                .Replace('/', Path.DirectorySeparatorChar)
                .Replace('\\', Path.DirectorySeparatorChar);

            var folder = Path.GetDirectoryName(normalized) ?? string.Empty;

            var rootName = GetRootFolderName(report);
            if (string.IsNullOrWhiteSpace(rootName))
                return folder;

            if (string.IsNullOrWhiteSpace(folder))
                return rootName;

            return $"{rootName}{Path.DirectorySeparatorChar}{folder}";
        }

        private static string BuildExpectedNamespace(ConsolidatedReport report, string? declaredInFile)
        {
            var rootName = GetRootFolderName(report);
            if (string.IsNullOrWhiteSpace(rootName))
                return string.Empty;

            if (string.IsNullOrWhiteSpace(declaredInFile))
                return rootName;

            var normalized = declaredInFile
                .Replace('/', Path.DirectorySeparatorChar)
                .Replace('\\', Path.DirectorySeparatorChar);

            var folder = Path.GetDirectoryName(normalized) ?? string.Empty;

            if (string.IsNullOrWhiteSpace(folder))
                return rootName.Replace(Path.DirectorySeparatorChar, '.');

            var full = $"{rootName}{Path.DirectorySeparatorChar}{folder}";
            return full.Replace(Path.DirectorySeparatorChar, '.');
        }

        private static string GetRootFolderName(ConsolidatedReport report)
        {
            if (string.IsNullOrWhiteSpace(report.TargetScope))
                return string.Empty;

            return Path.GetFileName(report.TargetScope.TrimEnd(
                Path.DirectorySeparatorChar,
                Path.AltDirectorySeparatorChar));
        }

        private static bool HasNamespaceDrift(ArchitecturalClassificationItem item)
        {
            if (string.IsNullOrWhiteSpace(item.Namespace) ||
                string.IsNullOrWhiteSpace(item.DeclaredInFile))
            {
                return false;
            }

            var normalized = item.DeclaredInFile
                .Replace('/', Path.DirectorySeparatorChar)
                .Replace('\\', Path.DirectorySeparatorChar);

            var folder = Path.GetDirectoryName(normalized);
            if (string.IsNullOrWhiteSpace(folder))
                return false;

            var expectedSuffix = folder.Replace(Path.DirectorySeparatorChar, '.');

            return !item.Namespace.EndsWith(expectedSuffix, StringComparison.Ordinal);
        }

        private static string TranslateStatus(string? status)
        {
            return status switch
            {
                "Sem Referência Estrutural" => "Unreferenced",
                "Referenciado" => "Referenced",
                "Suspeito" => "Suspicious",
                "Confirmado" => "Confirmed",
                _ => status ?? string.Empty
            };
        }

        private static string TranslateRemoval(string? removal)
        {
            return removal switch
            {
                "Requer Análise" => "Review Required",
                "Indicada" => "Suggested",
                "Não" => "No",
                "Sim" => "Yes",
                _ => removal ?? string.Empty
            };
        }

        private static string GetCoreDiagnosis(HygieneReport hygiene) =>
            hygiene.IsolatedCoreCount == 0
                ? "Core layer may be coupled with infrastructure or outer layers."
                : hygiene.IsolatedCoreCount < 3
                    ? "Core partially isolated but with limited structural protection."
                    : "Core isolation detected. Architectural boundaries appear preserved.";

        private static string GetNamespaceDiagnosis(HygieneReport hygiene) =>
            hygiene.NamespaceDriftCount > hygiene.TotalClasses * 0.15
                ? "High namespace drift detected. Folder structure may not reflect architectural boundaries."
                : hygiene.NamespaceDriftCount > hygiene.TotalClasses * 0.05
                    ? "Moderate namespace drift detected. Minor structural inconsistencies present."
                    : "Namespace hierarchy aligned with project structure.";

        private static string GetGlobalNamespaceDiagnosis(HygieneReport hygiene) =>
            hygiene.GlobalNamespaceCount > 0
                ? "Global namespace usage detected. This may indicate legacy code or architectural leakage."
                : "No global namespace usage detected.";

        private static string GetUnresolvedDiagnosis(StructuralCandidateAnalysisBreakdown breakdown) =>
            breakdown.ProbabilisticConfirmed > 0
                ? "Potential dead or orphaned code detected through structural analysis."
                : "No unresolved structural candidates detected.";

        private static string GetSolidDiagnosis(SolidResult? solid) =>
            (solid?.Alerts.Count ?? 0) > 5
                ? "Multiple SOLID violations detected. Design refactoring recommended."
                : (solid?.Alerts.Count ?? 0) > 0
                    ? "Minor SOLID design alerts detected."
                    : "No SOLID design alerts detected.";

        private static string GetImplicitCouplingDiagnosis(
            HygieneReport hygiene,
            ImplicitCouplingResult? implicitCoupling)
        {
            double couplingRating =
                hygiene.TotalClasses == 0
                    ? 0
                    : (implicitCoupling?.Suspicions.Count ?? 0) / (double)hygiene.TotalClasses;

            return couplingRating switch
            {
                <= 0.02 => "Implicit coupling is minimal. Modules appear structurally independent.",
                <= 0.05 => "Minor implicit coupling patterns detected. Monitor for architectural drift.",
                <= 0.10 => "Implicit coupling emerging between modules. Architectural boundaries may be weakening.",
                <= 0.20 => "Significant implicit coupling detected. Hidden dependencies may reduce modularity.",
                _ => "Critical implicit coupling detected. System architecture may be entangled."
            };
        }

        private static string Html(string? text)
        {
            if (string.IsNullOrEmpty(text))
                return string.Empty;

            return text
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;")
                .Replace("'", "&#39;");
        }

        private static int CountDistinctNamespaces(IReadOnlyList<ArchitecturalClassificationItem> items)
        {
            return items
                .Select(i => i.Namespace?.Trim())
                .Where(ns => !string.IsNullOrWhiteSpace(ns))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .Count();
        }
    }
}